version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-test
    host_name: jenkins-test
    ports: 
      - "8080:8080"
    volumes:
      - "./configs/jenkins-config:/var/jenkins_home"
    networks:
      - test-net
networks:
  test-net:
